name: Get Citation Data

on: 
  schedule:
    - cron: '0 8 * * *'  
  workflow_dispatch:  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4  

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-setuptools  
        pip3 install -r requirements.txt  

    - name: Run data collection script
      run: |
        cd ./google_scholar_crawler  
        python3 main.py  

    - name: Commit and push changes to GitHub
      run: |
        cd ./results  
        git init  
        git config --local user.name "${GITHUB_ACTOR}"  
        export remote_repo="https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"  
        git add *.json  
        git commit -m "Updated Citation Data"  
        git push "${remote_repo}" HEAD:google-scholar-stats --force  

      env:
        GOOGLE_SCHOLAR_ID: ${{ secrets.GOOGLE_SCHOLAR_ID }}  
